---
- name: Provision VM and Join to Domain
  hosts: localhost
  gather_facts: False

  vars:
    vm_name: "{{ lookup('env','New-VM') }}"
    ad_domain: uat-cluster.local
    ad_user: Administrator
    ad_password: Login@786

  tasks:
  - name: Set VM Name
    command: echo "Setting VM name to {{ vm_name }}"
  
  - name: Install required packages
    package:
      name:
        - realmd
        - sssd
      state: present

  - name: Join the AD domain
    command: realm join --user={{ ad_user }} {{ ad_domain }} --install=/ -U {{ ad_user }}%{{ ad_password }}
    register: join_result
    ignore_errors: yes

  - name: Check the AD join result
    fail:
      msg: "Unable to join the AD domain, {{ join_result.stderr }}"
    when: join_result.rc != 0

  - name: Restart SSSD service
    service:
      name: sssd
      state: restarted
      enabled: yes
