---
- name: Provision VM and Join to Domain
  hosts: all
  gather_facts: False
  become: yes
  become_user: root
  become_method: sudo

  vars:
    new_hostname: Name-Changed
    ad_domain: uat-cluster.local
    ad_user: Administrator
    ad_password: Login@786

  tasks:
  - name: Set the new hostname
    hostname:
      name: "{{ new_hostname }}"
    register: hostname_changed

  - name: Update hostname in /etc/hosts
    lineinfile:        
      path: /etc/hosts
      regexp: '^127\.0\.1\.1\s.*'
      line: '127.0.1.1 {{ new_hostname }}'
    when: hostname_changed.changed

  - name: Reboot if hostname changed
    command: "shutdown -r now"
    when: hostname_changed.changed
  
  - name: Install required packages
    package:
      name:
        - realmd
        - sssd
      state: present

  - name: Join the AD domain
    command: sudo realm -v join {{ ad_domain}}%{{ ad_password }}
    register: join_result
    ignore_errors: yes

  - name: Check the AD join result
    fail:
      msg: "Unable to join the AD domain, {{ join_result.stderr }}"
    when: join_result.rc != 0

  - name: Restart SSSD service
    service:
      name: sssd
      state: restarted
      enabled: yes
