---
- name: Join Ubuntu VM to Windows AD
  hosts: all
  vars:
    domain_admin_password: Login@786
  
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - realmd
        - sssd
        - sssd-tools
        - adcli
        - krb5-user

    - name: Join the AD domain
      become: yes
      become_user: root
      become_method: sudo
      shell: "echo {{ domain_admin_password }} | realm join --user=Administrator@uat-cluster.local --stdin-password"
      # Be cautious with storing passwords in playbooks. You might want to use Ansible Vault to securely manage secrets.

    - name: Configure SSSD
      template:
        src: sssd.conf.j2
        dest: /etc/sssd/sssd.conf
      notify:
        - restart sssd

  handlers:
    - name: restart sssd
      service:
        name: sssd
        state: restarted
