---
- name: Join Ubuntu VM to Windows AD
  hosts: all
  vars:
    domain_admin_password: Login@786
  
  tasks:
    - name: Add domain name and IP to /etc/hosts
      become: yes
      become_user: root
      become_method: sudo
      lineinfile:
        path: /etc/hosts
        line: '192.168.4.80 uat-cluster.local'
        state: present
        
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - realmd
        - sssd
        - sssd-tools
        - adcli
        - krb5-user

    - name: Join the AD domain
      become: yes
      become_user: root
      become_method: sudo
      shell: "realm -v join uat-cluster.local"
      args:
        stdin: Login@786
      # Be cautious with storing passwords in playbooks. You might want to use Ansible Vault to securely manage secrets.
